# Generated by Django 5.2.8 on 2025-11-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredients', models.TextField(blank=True, help_text='Ingredientes separados por comas o saltos de línea')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, help_text='Calificación de 1.0 a 5.0', max_digits=3)),
                ('preparation_time', models.CharField(blank=True, default='15-20 min', max_length=50)),
                ('portions', models.CharField(blank=True, default='1 persona', max_length=50)),
                ('badges', models.CharField(blank=True, choices=[('recomendado', '⭐ Recomendado'), ('vegano', '🌱 Vegano'), ('vegetariano', '🥕 Vegetariano'), ('sin-gluten', '🍞 Sin Gluten'), ('picante', '🌶️ Picante')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.categoria')),
            ],
            options={
                'verbose_name': 'Ítem del Menú',
                'verbose_name_plural': 'Ítems del Menú',
                'ordering': ['categoria__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Formatos: JPEG, PNG, WebP. Tamaño máximo: 2MB', upload_to='menu_images/%Y/%m/%d/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.itemmenu')),
            ],
            options={
                'verbose_name': 'Imagen del Ítem',
                'verbose_name_plural': 'Imágenes del Ítem',
                'ordering': ['orden'],
            },
        ),
    ]
