# Generated by Django 5.2.9 on 2026-01-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmenu',
            name='badges',
            field=models.CharField(blank=True, choices=[('recomendado', '⭐ Recomendado'), ('Desayunos', ' Desayunos'), ('Almuerzos', ' Almuerzos'), ('Especiales', 'Especiales'), ('Escurcion', 'Escurcion')], max_length=50),
        ),
    ]
